version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: veris
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql

    www:
        image: cristianid/grupo03tg-www:latest
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

volumes:
    persistent:
